version: '3'

services: 
  elasticsearch:
    image: 'elasticsearch:7.10.1'
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
  
  kibana:
    image: 'kibana:7.10.1'
    environment: 
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on: 
      - elasticsearch

  logstash:
    image: 'dalysama/logstash'
    environment: 
      XPACK_MONITORING_ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes: 
      - .\logstash\conf:/usr/share/logstash/pipeline/
    depends_on: 
      - elasticsearch
      - rabbitmq

  rabbitmq:
    image: 'dalysama/rabbitmq'
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
volumes: 
  esdata:
    driver: local